logging:
  level:
    org: debug

server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - ProxyForward
      routes:
        - id: modify_image_router
          uri: no://op
          predicates:
            - Path=/**
          filters:
            - name: ModifyImageSize
              args:
                responseHeaderName: Content-Type
                regexp: image/.*
